### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by probablykasper** [adamwatters/vscode-color-pick#3]
Great work on this extension, really glad you made it! However I would have something different in mind, so I'm just sharing my thoughts of an ideal color picker plug-in. These are just suggestions.

- When executing the "Pick Color" command, it should open as a pop-up above or below the cursor, instead of opening a new tab.
- When closing the pop-up using enter, it inserts the text into the editor and replaces the currently selected text.
- When closing by using cmd+c/ctrl+c, it should copy the color code to clipboard instead of inserting.
- The pop-up should let you switch the color code type. It should support HEX and RGB, and both should have alpha support.
- The extension should detect if the cursor is currently inside a color code, and when closing the pop-up with enter, it should update that code.
- Maybe have a shortcut that lets you click on color values to open the color picker (like if you cmd+click the value).

I really like [this](https://atom.io/packages/color-picker) color picker extension for Atom, which looks like this:
![image](https://user-images.githubusercontent.com/11315492/57524712-e9359600-7328-11e9-93ce-0acd3bd28f64.png)

**Comment by adamwatters** [comment]
@SpectralKH thanks for the feedback!

1) The color picker opening as it’s own page isn’t likely to change - I built this using the Webview API meaning its basically a web app running inside VSCode. Maybe in the future we’ll be able to embed Webviews in pop-ups? Seems possible and useful.

2) I like the suggested behaviors suggested for closing with enter vs ctr-c

3) alpha-support is the next thing i’ll add - hopefully today!

4) pulling the color from the current cursor position should be easily doable and is the next thing i want to add after alpha

5) other methods of opening the picker also in the works 👍
