### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by 4A47** [adamwatters/vscode-color-pick#7]
Really nice extension, thanks.

Any way to disable the notifications that the colour has been copied to clipboard? Don't think it should be necessary every time.

Also each time I leave the Color Pick window and go back, it resets to having copy as RGBA checked, would it be possible to maintain the check box selection?

**Comment by adamwatters** [comment]
Yes and yes.

I think the pop-ups are kind of annoying, but I think it’s useful to notify the user that the colors are being copied to their clipboard automatically. Maybe one message in the UI that updates when the color changes would be better?

Persisting state so the color picker doesn’t reset is definitely possible and i agree it will make the ux a lot nicer - should be added in the next few day. Thanks for the feedback! 😁🙏

**Comment by 4A47** [comment]
Yeah I think having a message in the UI would be preferable.

Good to hear, looking forward to the improvements, cheers.

**Comment by adamwatters** [comment]
> Also each time I leave the Color Pick window and go back, it resets to having copy as RGBA checked, would it be possible to maintain the check box selection?

New release should be working as you described.

**Comment by 4A47** [comment]
> > Also each time I leave the Color Pick window and go back, it resets to having copy as RGBA checked, would it be possible to maintain the check box selection?
> 
> New release should be working as you described.

Working great when closing and reopening the color pick tab but not when the tab is left open. When you switch back to your code to paste then back again it resets to whatever whatever was selected when the tab was last closed. When im using it I leave the tab open as you are often testing different colours on different things.

**Comment by adamwatters** [comment]
> Working great when closing and reopening the color pick tab but not when the tab is left open. When you switch back to your code to paste then back again it resets to whatever was selected when the tab was last closed. When im using it I leave the tab open as you are often testing different colours on different things.

🤦‍♂ can't believe i missed that. look for a release with a fix later today 😄

**Comment by adamwatters** [comment]
@4A47 just published a new release with a fix
